// Writes catalog/REVIEW.md: a readable per-Topic table of the Catalog for human review.
import { writeFileSync } from 'node:fs'
import { topics } from '../catalog/catalog.ts'
import { catalog } from '../src/catalog/index.ts'
import { BATCH_SIZE } from '../src/catalog/order.ts'

const batchOf = new Map(catalog.map((e, i) => [e.id, Math.floor(i / BATCH_SIZE) + 1]))
const cell = (s = '') => s.replaceAll('|', '\\|')

let md = `# Catalog review\n\nGenerated by \`npm run catalog:review\`. Do not edit; edit \`catalog/catalog.ts\`.\n\n${catalog.length} Expressions, ${topics.length} Topics. "Batch" is when the Expression is introduced.\n`
for (const t of topics) {
  const rows = catalog.filter((e) => e.topic === t.id).sort((a, b) => batchOf.get(a.id)! - batchOf.get(b.id)!)
  md += `\n## ${t.name} (${rows.length})\n\n| Batch | Romanization | Hangul | English | Usage note | id |\n|---|---|---|---|---|---|\n`
  for (const e of rows) {
    md += `| ${batchOf.get(e.id)} | ${cell(e.romanization)} | ${cell(e.hangul)} | ${cell(e.english)} | ${cell(e.usageNote)} | \`${e.id}\` |\n`
  }
}
writeFileSync(new URL('../catalog/REVIEW.md', import.meta.url), md)
console.log('Wrote catalog/REVIEW.md')
